### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [johnvictorfs/simple-utilities-mod#32]
**Before creating this bug report I have checked that:**
- [x] Latest [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) for my Minecraft Version is installed
- [x] Latest version of [Simple HUD Utilies](https://curseforge.com/minecraft/mc-mods/simple-utilities) for my Minecraft Version is installed
- [x] There is no currently [open issue](https://github.com/johnvictorfs/simple-utilities-mod/issues) about my problem

---

_Sorry for omitting several parts of the template to make the issue clear as possible._

**System Information (please complete the following information):**
 - Minecraft Version [1.16.5]
 - Mod Version [2.1.3]
 - Java Version (JRE) [15.0.2]

<details>
<summary>Error Logs</summary>

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/27/21, 11:22 PM
Description: Initializing game

java.lang.RuntimeException: Config 'class net.johnvictorfs.simple_utilities.config.SimpleUtilitiesConfig' has not been registered
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.getConfigHolder(AutoConfig.java:56)
	at net.johnvictorfs.simple_utilities.hud.GameInfoHud.<init>(GameInfoHud.java:52)
	at net.minecraft.client.gui.hud.InGameHud.handler$ccp000$onInit(InGameHud:4836)
	at net.minecraft.client.gui.hud.InGameHud.<init>(InGameHud:159)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:559)
	at net.minecraft.client.main.Main.main(Main:177)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 15.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1255023120 bytes (1196 MB) / 1719664640 bytes (1640 MB) up to 9965666304 bytes (9504 MB)
	CPUs: 12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1180m -Xmx9500m
	Suspected Mods: Auto Config v1 Updated (autoconfig1u), Simple HUD Utilities (simple_utilities), Fabric Loader (fabricloader)
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		anvil_fix: AnvilFix 1.2.1-1.16
		appleskin: AppleSkin mc1.16.4-2.1.0
		architectury: Architectury 1.20.28
		artifice: Artifice 0.14.6+1.16.5
		attributefix: Attribute Fix {FABRIC} 1.0.2
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		battletowers: Battle Towers 3.3.4-1.16.4
		beefjerky: Beef Jerky 1.0.0
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.1
		betterthanmending: BetterThanMending 1.3.0
		blast: BLAST 1.5.2
		blue_endless_jankson: jankson 1.2.0
		bno: Basic Nether Ores 1.16.5-5.5.0-Fabric
		borderlessmining: Borderless Mining 1.0.6+1.16.2
		bowinfinityfix: Bow Infinity Fix rv9
		bright-ore: Bright Ore 0.2.14-1.16.5
		c2me: Concurrent Chunk Management Engine 0.1-SNAPSHOT
		cardinal-components-base: Cardinal Components API (base) 2.8.1
		cardinal-components-entity: Cardinal Components API (entities) 2.8.1
		carrier: Carrier 1.7.6
		cloth-api: Cloth API 1.5.50
		cloth-armor-api-v1: Cloth Armor API v1 1.5.50
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.50
		cloth-common-events-v1: Cloth Common Events v1 1.5.50
		cloth-config2: Cloth Config v4 4.11.26
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.50
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.50
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.50
		cloth-scissors-api-v1: Cloth Scissors API v1 1.5.50
		cloth-utils-v1: Cloth Utils v1 1.5.50
		coat: Coat 1.0.0-beta.10
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_github_nathanpb_safer: Safer 1.1.0
		com_github_wearblackallday_javautils: JavaUtils ab1e0ad736be1d2c2d74c68fa8e9e40e752f2d18
		cullleaves: Cull Leaves 2.1.0
		dashloader: DashLoader 1.4.6
		dimthread: DimensionalThreading 1.2.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.3-beta1
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		emerald_tools: Emerald Tools 1.1.3
		enchant_giver: Enchant Giver 1.0.3
		enchdesc: EnchantmentDescriptions 2.0.8
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.1
		expcontainer: Experience Container [XP] 1.15.1
		extrasounds: Extra Sounds 1.4.0
		fabric: Fabric API 0.37.1+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+6aebe11a7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+95b14da07d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f3e8589e7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+6afaa13c7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+5f6b94517d
		fabricloader: Fabric Loader 0.11.6
		fabrilousupdater: FabrilousUpdater 2.0
		fastbench: FastBench 2.3
		fastfurnace: FastFurnace 2.4
		ferritecore: FerriteCore 2.0.5
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.0.1
		fourinchknife-trueinfinity: True Infinity 1.0.1
		gbfabrictools: GBfabrictools 1.2.2+1.16
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		hitmarker: HitMarker 1.0a-1.16.2
		ingameime: IngameIME 1.6.3
		inmis: Inmis 2.2.1-1.16.5
		inventorypause: Inventory Pause 1.0.6
		inventorysorter: Inventory Sorter 1.7.9-1.16
		invtrashslot: InvTrashSlot 1.0.2
		io_activej_activej-codegen: activej-codegen 4.2
		io_activej_activej-serializer: activej-serializer 4.2
		iris: Iris 1.1.1-starline+build.434
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 15
		kirin: Kirin UI 1.7-1.16.2
		ktdatataglib: KtDataTagLib 1.4.0
		kyrptconfig: Kytpt Config 1.1.6-1.16
		leafmealone: Leaf Me Alone 2.1
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.6
		maelstrom_library: Maelstrom Library 1.0-1.16.5
		mcdw: MC Dungeons Weapons 3.2.0
		megane: megane 4.1.3
		megane-base: megane-base 4.1.3
		megane-runtime: megane-runtime 4.1.3
		megane-vanilla: megane-vanilla 4.1.3+1.16.5
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		microconfig: Microconfig 1.0.5
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.2-1.16.5
		modid: 1.17 Raw Ores for 1.16 1.0.0
		modmenu: Mod Menu 1.16.11
		moenchantments: Mo'Enchantments 1.15.0
		morevillagers-fabric: MoreVillagersFabric 1.4.1-SNAPSHOT
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		mousewheelie: Mouse Wheelie 1.7.3-newconfig.2+mc1.16.5
		net_gudenau_lib_unsafe: unsafe 1.4.1
		netheritems: Nether Items 1.1.0
		notenoughcrashes: Not Enough Crashes 3.2.0
		obsdncontainer: Obsidian Container [Experience Container Addon] 1.0.1
		omega-config: OmegaConfig 1.0.2
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
		playerabilitylib: Pal 1.2.1
		presencefootsteps: Presence Footsteps r29+1.16.4
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		reroll: Reroll 1.2.1-1.16.5
		respackopts: Resource Pack Options 1.4.2
		roughlyenoughitems: Roughly Enough Items 5.12.235
		roughlyenoughitems-api: REI (API) 5.12.235
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.235
		roughlyenoughitems-runtime: REI (Runtime) 5.12.235
		ruined_equipment: Ruined Equipment 1.2.4
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		schmucks: Schmucks 1.2.0
		simple_utilities: Simple HUD Utilities 2.1.3
		simpleplanes: simpleplanes 3.2.3
		slight-gui-modifications: 'Slight' GUI Modifications 1.7.1
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.2.0+IRIS3-build.49
		spellbound: Spellbound 1.3.0
		starlight: Starlight fabric-1.0.0-RC2-82ae5ca
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.2.2
		structure-helpers: Structure Helpers 3.0.0
		taxfreelevels: Tax Free Levels 1.1
		timeinabottle: Time in a Bottle 1.3-mc1.16.4-fabric
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.1.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.1
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		vanilladeathchest: VanillaDeathChest 2.0.6-fabric
		voxelmap: VoxelMap 1.10.15
		voyager: Voyager 1.0.0
		waterdripsound: Drip Sounds 0.2.1-1.16
		wthit: wthit 2.10.2
		yungsapi: YUNG's API 1.16.5-Fabric-6
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.47, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
```
</details>

**Comment by ChromaPIE** [comment]
Confirmed to be caused by another mod
