### ISSUE TITLE
Game crashing in the latest version of Fabric Loader

### ISSUE THREAD

**Issue by MarkinhosMLP** [johnvictorfs/simple-utilities-mod#49]
Using last version of FabricAPI, last of Fabric Loader and the last of the mod in 1.18.2.
The game simply crashes

java.lang.RuntimeException: Config 'class net.johnvictorfs.simple_utilities.config.SimpleUtilitiesConfig' has not been registered
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.getConfigHolder(AutoConfig.java:56)
	at net.johnvictorfs.simple_utilities.hud.GameInfoHud.<init>(GameInfoHud.java:53)
	at net.minecraft.client.gui.hud.InGameHud.handler$cjj000$onInit(InGameHud:12024)
	at net.minecraft.client.gui.hud.InGameHud.<init>(InGameHud:171)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:593)
	at net.minecraft.client.main.Main.main(Main:197)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by johnvictorfs** [comment]
Could you comment a mod list? I am a bit unsure just from this crash, but it seems you are running a 1.17 mod on 1.18? From this line:

```
at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
```
